name: test
on:
  pull_request_target:
    paths:
      - 'test/*'


jobs:
  testRun:
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ./test2
    - name: run
      run: cat test2/test/sometext.txt
