name: test
on:
  pull_request_target:
    paths:
      - 'test/*'


jobs:
  testRun:
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
    - name: Checkout AutoPkg recipes
      run: echo "its working"
